package cobo.writing.config.response

enum class CoBoResponseStatus(
    val code: Int,
    val message: String
) {

    SUCCESS(2000, "OK"),
    NO_DATA_CHANGES(2001, "SUCCESS, BUT NO DATA CHANGES"),
    CREATED(2010, "CREATED_SUCCESS"),
    UPDATED(2011, "UPDATED_SUCCESS"),


    BAD_REQUEST(4000, "BAD REQUEST"),
    EXPIRED_ASSIGNMENT(4001, "EXPIRED_ASSIGNMENT"),
    BAD_STATE_REQUEST(4002, "BAD STATE_REQUEST"),
    INVALID_RANGE(4001, "INVALID RANGE"),
    NOT_AUTHORIZATION(4011, "AUTHORIZATION TOKEN IS EMPTY"),
    NOT_FOUND_USER(4041, "USER NOT FOUND"),
    NOT_FOUND_DATA(4042, "NOT_FOUND DATA"),
    CHATGPT_ERROR(4043, "CHATGPT ERROR"),
}