version: '3'

services:
  auth-server:
    container_name: auth-server
    build: ./auth
    volumes:
      - auth_log:${AUTH_LOG_PATH}
      - auth_logs:${AUTH_LOGS_PATH}
    ports:
      - "8080:8080"
    networks:
      - cobo
  chat-server:
    container_name: chat-server
    build: ./chat
    volumes:
      - chat_log:${CHAT_LOG_PATH}
      - chat_logs:${CHAT_LOGS_PATH}
    ports:
      - "12041:12041"
    networks:
      - cobo
  writing-server:
    container_name: writing-server
    build: ./writing
    volumes:
      - files:${FILE_PATH}
      - writing_log:${WRITING_LOG_PATH}
      - writing_logs:${WRITING_LOGS_PATH}
    ports:
      - "12042:12042"
    networks:
      - cobo
  file-server:
    container_name: file-server
    build: ./file
    volumes:
      - files:${FILE_PATH}
      - file_log:${FILE_LOG_PATH}
      - file_logs:${FILE_LOGS_PATH}
    ports:
      - "12043:12043"
    networks:
      - cobo

  nginx:
    build: ./nginx
    image: nginx:stable-perl
    ports:
      - "80:80"
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-server
      - chat-server
      - writing-server
      - file-server
    networks:
      - cobo

networks:
  cobo:

volumes:
  files:
  auth_log:
  auth_logs:
  chat_log:
  chat_logs:
  writing_log:
  writing_logs:
  file_log:
  file_logs: